<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Diffuse</AssemblyName>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\Icon.ico</ApplicationIcon>
    <Configurations>Debug;Release;</Configurations>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <!--Projects-->
  <ItemGroup>
    <ProjectReference Include="..\DiffuseApp.Common\DiffuseApp.Common.csproj" />
  </ItemGroup>

  <!--TensorStack-->
  <ItemGroup>
    <PackageReference Include="TensorStack.WPF" Version="$(Version)" />
    <PackageReference Include="TensorStack.Python" Version="$(Version)" />
    <PackageReference Include="TensorStack.Upscaler" Version="$(Version)" />
    <PackageReference Include="TensorStack.Extractors" Version="$(Version)" />
    <PackageReference Include="TensorStack.Providers.DML" Version="$(Version)" />
  </ItemGroup>

  <!--Common-->
  <ItemGroup>
    <PackageReference Include="System.Linq.Async" Version="7.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
    <PackageReference Include="System.Management" Version="10.0.1" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.6" />
  </ItemGroup>

  <!--Binaries-->
  <ItemGroup>
    <Reference Include="CSnakes.Runtime">
      <HintPath>CSnakes.Runtime.dll</HintPath>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="OnnxStack.Adapter.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>

  <!--Images-->
  <ItemGroup>
    <Resource Include="Images\Diffuse-512.png" />
    <Resource Include="Images\Diffuse-Logo-512.png" />
    <Resource Include="Images\Diffuse-Logo-Long-64.png" />
    <Resource Include="Images\Icon.ico" />
  </ItemGroup>

  <!--Fonts-->
  <ItemGroup Condition="Exists('Fonts\Brands-Regular-400.otf')">
    <Resource Include="Fonts\Brands-Regular-400.otf" />
    <Resource Include="Fonts\Duotone-Solid-900.otf" />
    <Resource Include="Fonts\Light-300.otf" />
    <Resource Include="Fonts\Regular-400.otf" />
    <Resource Include="Fonts\Sharp-Light-300.otf" />
    <Resource Include="Fonts\Sharp-Regular-400.otf" />
    <Resource Include="Fonts\Sharp-Solid-900.otf" />
    <Resource Include="Fonts\Sharp-Thin-100.otf" />
    <Resource Include="Fonts\Solid-900.otf" />
    <Resource Include="Fonts\Thin-100.otf" />
  </ItemGroup>


  <!--Settings-->
  <ItemGroup>
    <None Update="Settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
